version: '3.1'

services:
  db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_db
    ports:
      - 5432:5432